apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sltzxn9zs-nodejs-gitops
  description: This is GitOps manifest for sltzxn9zs-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=sltzxn9zs-nodejs
    backstage.io/kubernetes-id: sltzxn9zs-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: sltzxn9zs-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:sltzxn9zs-nodejs
