apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sltzxn9zs-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:b21b333698d3c8a00dc604ccf84dee8a722a0508@sha256:3975ef6afd1134a2da9c7f687a6cfa3a89f25887a1f20048572fac99df7c7dfd
          name: container-image
